export default {
  baodanhao: "保单号",
  baodan: "保单扫描件",
  baoanren: "报案人",
  baoxianren: "被保险人",
  shenfen: "身份证复印件",
  yingyezhizhao: "营业执照或统一社会信用代码证复印件",
  xuke: "专利使用许可合同或许可备案证明",
  zhuanlihao: "专利号",
  zhengshu: "专利证书复印件",
  dengji: "专利登记簿副本或专利年费收据",
  lvxing: "相关合同及履行证据",
  beian: "备案证明",
  baogao: "专利评价报告",
  jiejian: "引用或借鉴的最接近技术或设计方案及产品样品",
  zuizao: "专利产品或方案最早公开的相关发布载体",
  qinquanfang: "被告侵权方名称",
  chanpin: "专利产品",
  qinquanyangpin: "涉嫌侵权产品样品",
  qinquanqudao: "涉嫌侵权产品的取得渠道及方式的说明及相关证明材料",
  xiangguan: "相关单据",
  qinquanxuanchuan: "涉嫌侵权产品的广告宣传资料",
  qinquanzhuti: "侵权人的主体资料或信息",
  qisu: "拟起诉金额和依据"
}